doctrine:
  meta:
      entity_path:
          - /../../src/Model/Entity
      auto_generate_proxies: false
      proxy_dir: path
      cache: null
  connection:
      driver: pdo_mysql
      host: 127.0.0.1
      dbname: test
      user: root
      password: ''
